### PR TITLE
Added TerrainCollider to SuperCollider.

### PR DESCRIPTION
**Pull request by Axuim**
Has a fast method (default, works most of the time) and a slow method or finding the closest point on surface.

Updated TerrainTest scene with character and camera.

### CODE REVIEW

**Comment by Axuim** [comment]
It seems I accidentally left a debug log in the slow method.  I am going to be away from a computer for a few weeks so if someone wishes to remove that post pull they can.

**Comment by Axuim** [comment]
Thought of a few more ways that it could be broken, closing until they are fixed or proven out.

**Comment by Axuim** [comment]
I take that back, something else in my use case was causing the problems.

**Comment by IronWarrior** [comment]
This has been a dramatic back and forth. I'll pull this sometime today and then merge it if you're okay with it's current state. I can remove the debug statements before I merge.

Either way great work! With this added all the default colliders are now supported. I never got a chance to sit down and work out the closest point on terrain problem, so it'll be fun reading through your code.

**Comment by Axuim** [comment]
Yeah sorry about that.  I should probably stop trying to do 5+ things at the same time. 

Anyways the code minus the debug statement should be good to go!

**Comment by IronWarrior** [comment]
Hey Axuim, I'm getting some issues with the terrain test scene. When I run it, the controller tends to clip through the ground fairly quickly. I've posted a gif of this below...were you encountering the same error? I'm using the latest version of Unity (5.2.2f1)

http://gfycat.com/SmoothGoldenChimpanzee

**Comment by Axuim** [comment]
I was not seeing that problem but I will give it another look when I get off work.

**Comment by Axuim** [comment]
This appears to be due to a bug in the super controller class where it doesn't compensate for the SphereCast radius in one case and as such doesn't find the ground.  I will close this pull request and submit a new one with that fix, terrain collision, and a small fix for off center SphereColliders.

**Pull request closed without merging**
