### PR TITLE
Terrain Collision, ProbeGround radius compensation, and SphereCollider center fix.

### PR DESCRIPTION
**Pull request by Axuim**
Added Terrain Collision.
Fix for SphereCast radius compensation in one case in ProbeGround.
SphereCollider closest point now takes into account the center property.

### CODE REVIEW

**Comment by Ulydev** [comment]
Wow. Just wow.

**Comment by Axuim** [comment]
Hopefully that is a good wow...

**Comment by IronWarrior** [comment]
^Haha I was wondering the same thing...I'm going to assume it's an extremely positive "wow".

Anyways, I pulled the latest and the clipping through the ground issue seems to be gone, but I'm still getting some clipping into the edges of the terrain, which can be seen here.

http://i.imgur.com/ObwNEtR.png

I tried both the fast and non-fast methods of the function. Are you getting this on your end? I'll investigate this further tonight when I've got a chance.

**Comment by Axuim** [comment]
The slow method should have solved that specific problem but thinking back on it I am not sure I am finding the correct triangle in higher resolution heightmaps.  I will look at it again after I get off work.

**Comment by IronWarrior** [comment]
Hey Axium,

I looked into your code and wasn't able to figure out the error...but after spending some time perusing your stuff I had actually learned enough to be able to write my own branch for the TerrainCollider support, which I just merged to master. Mine is accurate and works well, but I'm not sure if it's the most efficient way possible to do it.

If you do follow through with your branch and it turns out to be both accurate and more efficient than mine, feel free to update it and I can merge it in.

**Comment by Axuim** [comment]
I am glad you were able to get your own implementation working!  Work picked up so I haven't had that much time to do anything with mine and probably won't for a while so I will just close this.

**Pull request closed without merging**
